apiVersion: v1
kind: Service
metadata:
  name: airbyte-openmetrics-exporter
  namespace: airbyte
  labels:
    app.kubernetes.io/name: airbyte-openmetrics-exporter
    app.kubernetes.io/component: metrics-exporter
    prometheus.io/scrape: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: airbyte-openmetrics-exporter
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics
